const FETCH = 'FETCH';

const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGIN_START = 'LOGIN_START';

const SERVER_ERROR = 'SERVER_ERROR';

export {
  FETCH,

  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGIN_START,

  SERVER_ERROR
}
